# 开发环境配置
app:
  prefix: '/v1/api'
  port: 9001
  logger:
    # 项目日志存储路径，相对路径（相对本项目根目录）或绝对路径
    dir: '../logs'
  # 文件相关, 开发环境
  file:
    # location 文件上传后存储目录，相对路径（相对本项目根目录）或绝对路径
    location: '../upload'
    # 文件服务器地址，这是开发环境的配置 生产环境请自行配置成可访问域名
    domain: 'http://123.249.74.79:9001'
    # 文件虚拟路径, 必须以 / 开头
    serveRoot: '/static'
# 数据库配置
db:
  mysql:
    host: '123.249.74.79'
    username: 'root'
    password: '123456'
    database: 'service-one-dev'
    port: 3306
    charset: 'utf8mb4'
    logger: 'advanced-console'
    logging: true
    multipleStatements: true
    dropSchema: false
    synchronize: true
    supportBigNumbers: true
    bigNumberStrings: true

# redis 配置
redis:
  host: '123.249.74.79'
  port: 6379
  db: 0
  keyPrefix: 'nest:'

# jwt 配置
jwt:
  secretkey: 'zANDwNQVFzxlfG9myPxVWAkq4iXJEPhI'
  expiresin: '1h'
  refreshExpiresIn: '2h'
# 权限 白名单配置
perm:
  router:
    whitelist: [{ path: '/v1/api/register', method: 'POST'  }, { path: '/v1/api/login', method: 'POST' }, { path: '/v1/api/logout', method: 'GET' }, { path: '/v1/api/perm/{id}', method: 'GET' }, { path: '/v1/api/oss/upload', method: 'POST' }, { path: '/v1/api/getUserInfo', method: 'GET' }]

# 用户相关
# 初始密码， 重置密码
user:
  initialPassword: 'ABC#123'
